### ISSUE TITLE
Licensing unclear

### ISSUE THREAD

**Issue by peacememories** [akasten/signingframework#2]
We are currently using signingframework in our application https://github.com/researchstudio-sat/webofneeds and have just published our first version to Maven Central.
Unfortunately, the way we consume this library (a local repository) is not compatible with hosting on Central, so users cannot currently depend on our libraries.
Since this repository seems to be inactive, we are contemplating forking it and hosting signingframework on Maven Central under our groupId.
Before we can do this we need to know if the license of this library supports it, though.

Since there is no license information (that I could find) in the repository, and the linked site seems to be down, I though I would ask here:
What license is this library released under? And in case the license is not permissive enough for us to fork the project as we discussed, could we get permission to do this from you?

Thanks for creating this library and taking the time to read this.

**Comment by akasten** [comment]
Thank you for your interest in the signing framework. To be honest, I am not an expert in licensing and I haven't thought about a particular license yet. At the moment, however, I'd prefer to use LGPLv3. Is your usage of the signing framework compatible with this license?

I should also mention that I am not the main developer of the framework. I've just contacted the main developer and asked him about his preferences about the licensing issue. As soon as I receive a reply from him, I'll leave another comment.

**Comment by peacememories** [comment]
Thanks for replying so quickly!
LGPLv3 would suit us perfectly, all we need is permission to share the code in source and compiled form (that way we can upload it to Maven Central), so basically any open source license would do.

**Comment by akasten** [comment]
I received a reply from the main developer. He is fine with using LGPL v3, so I've just added a LICENSE file to the root folder of the repository (and thereby licensed the signing framework under LGPL v3).

**Comment by peacememories** [comment]
Thanks so much! :)
I’ll be at work again on Tuesday and will probably do the publishing to Central then.
I think this issue is resolved so I’ll close it :)

Have a nice day!
